[theme]
primaryColor = "#E63946"          # Kolor przycisków i aktywnych elementów
backgroundColor = "#1D3557"       # Kolor tła strony
secondaryBackgroundColor = "#457B9D" # Kolor bocznego paska i widżetów
textColor = "#F1FAEE"             # Kolor tekstu
font = "sans serif"               # Rodzaj czcionki